#!/bin/bash

# This script acts as a wrapper to the simulation executable

##### Constants
M1=50; M2=70; M3=100;
N1=20; N2=30; N3=50;
F1=1; F2=2; F3=3;

##### Functions
function plot_results {

  until [ $(pidof slottedAloha_stage3.out | wc -l) -eq 0 ]; do
    sleep 10
  done

  for M in $M1 $M2 $M3; do
    gnuplot -p -e "set xlabel 'probability of retransmission p (busy stations)'; set ylabel 'throughput S';\
    set xrange [0:1]; set yrange [0:]; set grid x y2; set key Left left top box\
    title 'throughput'; unset ytics; set y2tics; plot\
    'total_M${M}_N${N1}_FB${F1}_stage3.out' using 1:2 with lines title '$M st, $N1 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F2}_stage3.out' using 1:2 with lines title '$M st, $N1 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F3}_stage3.out' using 1:2 with lines title '$M st, $N1 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N2}_FB${F1}_stage3.out' using 1:2 with lines title '$M st, $N2 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F2}_stage3.out' using 1:2 with lines title '$M st, $N2 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F3}_stage3.out' using 1:2 with lines title '$M st, $N2 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N3}_FB${F1}_stage3.out' using 1:2 with lines title '$M st, $N3 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F2}_stage3.out' using 1:2 with lines title '$M st, $N3 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F3}_stage3.out' using 1:2 with lines title '$M st, $N3 ch, $F3 buf' lw 2 smooth bezier"

    gnuplot -p -e "set xlabel 'probability of retransmission p (busy stations)'; set ylabel 'delay D';\
    set xrange [0:1]; set yrange [0:]; set grid x y2; set key Left left top box\
    title 'delay'; unset ytics; set y2tics; plot\
    'total_M${M}_N${N1}_FB${F1}_stage3.out' using 1:3 with lines title '$M st, $N1 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F2}_stage3.out' using 1:3 with lines title '$M st, $N1 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F3}_stage3.out' using 1:3 with lines title '$M st, $N1 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N2}_FB${F1}_stage3.out' using 1:3 with lines title '$M st, $N2 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F2}_stage3.out' using 1:3 with lines title '$M st, $N2 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F3}_stage3.out' using 1:3 with lines title '$M st, $N2 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N3}_FB${F1}_stage3.out' using 1:3 with lines title '$M st, $N3 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F2}_stage3.out' using 1:3 with lines title '$M st, $N3 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F3}_stage3.out' using 1:3 with lines title '$M st, $N3 ch, $F3 buf' lw 2 smooth bezier"

    gnuplot -p -e "set xlabel 'probability of retransmission p (busy stations)'; set ylabel 'mean busy stations';\
    set xrange [0:1]; set yrange [0:]; set grid x y2; set key Left right bottom box\
    title 'mean busy stations'; unset ytics; set y2tics; plot\
    'total_M${M}_N${N1}_FB${F1}_stage3.out' using 1:4 with lines title '$M st, $N1 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F2}_stage3.out' using 1:4 with lines title '$M st, $N1 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F3}_stage3.out' using 1:4 with lines title '$M st, $N1 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N2}_FB${F1}_stage3.out' using 1:4 with lines title '$M st, $N2 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F2}_stage3.out' using 1:4 with lines title '$M st, $N2 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F3}_stage3.out' using 1:4 with lines title '$M st, $N2 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N3}_FB${F1}_stage3.out' using 1:4 with lines title '$M st, $N3 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F2}_stage3.out' using 1:4 with lines title '$M st, $N3 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F3}_stage3.out' using 1:4 with lines title '$M st, $N3 ch, $F3 buf' lw 2 smooth bezier"

    gnuplot -p -e "set xlabel 'throughput S'; set ylabel 'delay D';\
    set xrange [0:]; set yrange [0:]; set grid x y2; set key Left right top box\
    title 'delay / throughput'; unset ytics; set y2tics; plot\
    'total_M${M}_N${N1}_FB${F1}_stage3.out' using 2:3 with lines title '$M st, $N1 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F2}_stage3.out' using 2:3 with lines title '$M st, $N1 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N1}_FB${F3}_stage3.out' using 2:3 with lines title '$M st, $N1 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N2}_FB${F1}_stage3.out' using 2:3 with lines title '$M st, $N2 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F2}_stage3.out' using 2:3 with lines title '$M st, $N2 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N2}_FB${F3}_stage3.out' using 2:3 with lines title '$M st, $N2 ch, $F3 buf' lw 2 smooth bezier,\

    'total_M${M}_N${N3}_FB${F1}_stage3.out' using 2:3 with lines title '$M st, $N3 ch, $F1 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F2}_stage3.out' using 2:3 with lines title '$M st, $N3 ch, $F2 buf' lw 2 smooth bezier,\
    'total_M${M}_N${N3}_FB${F3}_stage3.out' using 2:3 with lines title '$M st, $N3 ch, $F3 buf' lw 2 smooth bezier"
  done
}  # end of plot_results

function usage {
    echo "usage: $0 [[-r (runs simulation and plots results)] | [-p (plots results)]] | [-h (this message)]]"
}  # end of usage

function run_simulation {
  for M in $M1 $M2 $M3; do
    sed -i -- "s/define M [0-9][0-9]*/define M ${M}/g" ./slottedAloha_stage3.c

    for N in $N1 $N2 $N3; do
      sed -i -- "s/define N [0-9][0-9]*/define N ${N}/g" ./slottedAloha_stage3.c

      for F in $F1 $F2 $F3; do
        sed -i -- "s/define FB [0-9]*/define FB ${F}/g" ./slottedAloha_stage3.c

        gcc slottedAloha_stage3.c -O3 -lm -o slottedAloha_stage3.out
        ./slottedAloha_stage3.out > total_M${M}_N${N}_FB${F}_stage3.out&
      done
    done
  done
}  # end of run_simulation

##### Main
case $1 in
  -r | --run )  run_simulation
                plot_results
                exit
                ;;
  -p | --plot ) plot_results
                exit
                ;;
  -h | --help ) usage
                exit
                ;;
  * )           usage
                exit 1
esac